version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: projet_btssnir
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "9906:3306"
    volumes:
      - ./projet_web-main/.projet_btssnir:/var/lib/mysql/
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
  web:
    build: ./
    links:
      - db
    volumes:
      - ./projet_web-main:/var/www/html/
    ports:
      - "8080:80"
    stdin_open: true
    tty: true