version: '3'

services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8081:3306"
  web:
    build: .
    container_name: php_web
    depends_on:
      - database
    volumes:
      - $(pwd)/projet_web-main:/var/www/html/
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
