version: '3'

services:
  database:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./database:/var/lib/mysql
  web:
    build: .
    container_name: php_web
    depends_on:
      - database
    volumes:
      - ./projet_web-main:/var/www/html/
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
  pma:
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - database
    environment:
      PMA_HOST: database
